### ISSUE TITLE
Request failed with error code 500

### ISSUE THREAD

**Issue by RakibRyan** [HalilCan/codeGPT-assistant-extension#1]
I did as instructed & the test seemed to write code on the puppeter browser but did not come to the codegpt extension instead showed error code 500. 
Also it seems the request is opening on a incognito tab it's asking me to log in everytime I open vscode & codegpt.

**Comment by HalilCan** [comment]
1 - Error 500: Have you updated the extension recently? The chatgpt interface changed, but I fixed things so 1.1.4 should work on your end too.
2 - Logging in repeatedly: It's a different version of chrome - but that doesn't matter for the problem you mentioned. The solution to that is _probably_ saving cookies so that we don't have to log in again. I'll look into that, but feel free to make your own PR if you have the time.

**Comment by HalilCan** [comment]
Fixed the superfluous logging in problem. Check the newest commit or the marketplace for 1.2.0. Error 500 was due to the recent interface update I believe, which was  fixed 1.1.4+.
